# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DaveLuo
brief-intro: DaveLuo
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daveluo.win" # the base hostname & protocol for your site

#permalink: /dd:year/:month/:day/:title/
permalink: /:year-:month-:day-:title/

description_footer: 点点滴滴

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
